### ISSUE TITLE
PaymentScreenURL is malformed in test mode.

### ISSUE THREAD

**Issue by xavierbarbosa** [icepay/icepay#1]
When retrieving the PaymentScreenURL to Icepay_Api_Webservice's checkOut.

```
object(Icepay_TransactionObject)[790]
  protected 'data' => 
    object(stdClass)[784]
      ...
      public 'MerchantID' => int **Removed due to security**
      public 'Timestamp' => string '2015-09-09T10:50:19.904Z' (length=24)
      public 'Amount' => int 24400
      public 'Country' => string 'NL' (length=2)
      public 'Currency' => string 'EUR' (length=3)
      public 'Description' => string '' (length=0)
      public 'EndUserIP' => string '192.168.56.1' (length=12)
      public 'Issuer' => string 'ING' (length=3)
      public 'Language' => string 'NL' (length=2)
      public 'OrderID' => string '601' (length=3)
      public 'PaymentID' => int **Removed due to security**
      public 'PaymentMethod' => string 'IDEAL' (length=5)
      public 'PaymentScreenURL' => string 'http://testmode.icepay.eu/payment/start/**Removed due to security**/IDEAL/ING/NL/NL/EUR/24400/Merchant **** OrderID 601' (length=107)
      ...
```

**Comment by RicardoJ** [comment]
Thank you for creating a issue. We are currently not aware of this issue.

What happends if you use [urlencode](http://il.php.net/manual/en/function.urlencode.php) function on the PaymentScreenURL string?

```php
urlencode($transactionObj->getPaymentScreenURL())
```

I think due to the spaces in the url, the url is malformed and therefore is not usable at your end. Let us know if this works.

**Comment by xavierbarbosa** [comment]
Hi Ricardo.

Thank you for your answer! The url indeed works. But i though it was strange that the url contained those spaces. But maybe that is out of your control since thats what returned from the gateway.

If this is indeed the case. We can close this issue.

**Comment by RicardoJ** [comment]
Hi @xavierbarbosa!

The test mode url contains these extra unnecessary information like the payment description. This url is returned from the gateway and is only solveable by using the urlencode function in your case.

I'll close this case for now.
