### ISSUE TITLE
Problems with payment > 10K

### ISSUE THREAD

**Issue by mgn117** [ICEPAY/icepay#6]
Hello,

We are having problems with order with an amount higher then 10.000 EUR. On the checkout page, there are no payment methods visible anymore. For order below 10.000 EUR we don't have problems. ICEPAY already changed the max. allowed order value to 20.000 EUR but the problem of the no shown payment methods still remain.

We are using Magento version 1.9.2.1. and the ICEPAY advanced 1.2.9 module

**Comment by tsygankov** [comment]
Hi mgn117,

Can you please try to refreshing payment method configuration settings? 

Please refer to the ICEPAY Magento Advanced Module Manual, section 7.7, step 5
https://icepay.com/downloads/pdf/manuals/magento/icepay-manual-magento-advanced.pdf

If you require any further information, please let me know.

**Comment by mgn117** [comment]
Hello,

Your collegue also told me to click on the 'Get Paymentmethods' in the
backend. Now I did the same action again, and again the paymentmethods are
not visible in the checkout. See screenshot below:
[image: Inline afbeelding 1]
Wat is happening right here?!

Met vriendelijke groet/Kind regards,
Martijn Greven

Dutchworld IT Solutions
EBUSINESS INTEGRATORS


Internet: www.dutchworld.nl
Phone: +31(0)30 2293118
Mobile: +31(0)6 23725608
Email: martijn@dutchworld.nl <martijngreven@dutchworld.nl>
Skype: martijngreven_nl

This message is intended solely for the person to whom it is addressed and
may contain confidential or privileged information. If you have received
this message in error please notify the sender and destroy this e-mail and
any attachments. In addition, you must not copy, distribute or take any
action based on this message or any information contained herein.

2016-10-31 15:09 GMT+01:00 tsygankov <notifications@github.com>:

**Comment by tsygankov** [comment]
Can you please send the screenshot to icepay@balticsolutions.lv?

Can you please also check if ICEPAY settings are correct (merchant ID\secret code)?

If settings are correct, please contact us by email. We may request more information about your website\merchant account.

**Comment by mgn117** [comment]
Hello,

I've checked the ID and secret code and they are good.

Attached again the screenshot of the cart, as you asked for to send to
icepay@balticsolutions.lv: <icepay@balticsolutions.lv>
[image: Inline afbeelding 1]

Merchant id: 26697
Secret code: j9Q8Rcr7Z5Apb4F6Utk3YTn7z6GKu4s8EDf5y9H3

Met vriendelijke groet/Kind regards,
Martijn Greven

Dutchworld IT Solutions
EBUSINESS INTEGRATORS


Internet: www.dutchworld.nl
Phone: +31(0)30 2293118
Mobile: +31(0)6 23725608
Email: martijn@dutchworld.nl <martijngreven@dutchworld.nl>
Skype: martijngreven_nl

This message is intended solely for the person to whom it is addressed and
may contain confidential or privileged information. If you have received
this message in error please notify the sender and destroy this e-mail and
any attachments. In addition, you must not copy, distribute or take any
action based on this message or any information contained herein.

2016-10-31 16:18 GMT+01:00 tsygankov <notifications@github.com>:

**Comment by tsygankov** [comment]
For security reasons please do not publish any sensitive information on GitHub. I've edited your comments and removed your account details. I will ask ICEPAY to reset your secret key, because it still can be available in search engine cache.

**Comment by tsygankov** [comment]
We will try to reproduce the problem and get back to you soon.

**Comment by tsygankov** [comment]
Hi,

I've tried to reproduce the problem using your merchant account settings and payment methods are showing up (see att.).

![att2](https://cloud.githubusercontent.com/assets/15112699/19873319/b19c27c8-9f94-11e6-88ab-f772b27836f0.png)
![att1](https://cloud.githubusercontent.com/assets/15112699/19873318/b1997028-9f94-11e6-88be-e85c6b004167.png)

Payment methods are also filtered by country. Can you please specify web-shop country settings and consumer country settings (billing\shipping address)?

Do you use multistore mode? 

Do you have access to the database? Would it be be possible to execute several SQL queries and send me the results?

**Comment by tsygankov** [comment]
Hi,

Do you have any updates?

**Comment by mgn117** [comment]
Hi,

On our test website with the same ID and secret key, I installed the new
module 1.2.11 and I tried it again to do a 'get payments' but without any
luck.

Met vriendelijke groet/Kind regards,
Martijn Greven

Dutchworld IT Solutions
EBUSINESS INTEGRATORS


Internet: www.dutchworld.nl
Phone: +31(0)30 2293118
Mobile: +31(0)6 23725608
Email: martijn@dutchworld.nl <martijngreven@dutchworld.nl>
Skype: martijngreven_nl

This message is intended solely for the person to whom it is addressed and
may contain confidential or privileged information. If you have received
this message in error please notify the sender and destroy this e-mail and
any attachments. In addition, you must not copy, distribute or take any
action based on this message or any information contained herein.

2016-11-01 19:04 GMT+01:00 tsygankov <notifications@github.com>:

**Comment by mgn117** [comment]
Hello,

Can you please answer my question asap?

Thanks!

Met vriendelijke groet/Kind regards,
Martijn Greven

Dutchworld IT Solutions
EBUSINESS INTEGRATORS


Internet: www.dutchworld.nl
Phone: +31(0)30 2293118
Mobile: +31(0)6 23725608
Email: martijn@dutchworld.nl <martijngreven@dutchworld.nl>
Skype: martijngreven_nl

This message is intended solely for the person to whom it is addressed and
may contain confidential or privileged information. If you have received
this message in error please notify the sender and destroy this e-mail and
any attachments. In addition, you must not copy, distribute or take any
action based on this message or any information contained herein.

2016-10-31 15:09 GMT+01:00 tsygankov <notifications@github.com>:

**Comment by tsygankov** [comment]
Hi,

Sorry, I missed you reply for some reason.

I will do a clean install of Magento v1.9.2.1. and the ICEPAY Payment Module v1.2.11 and try to reproduce the problem again. I will create a video or screenshots of the installation process and send them to you email. 

If you need any urgent help, please contact me on Skype. I've sent you a contact request. We can arrange a video call (screen sharing) and try to solve the problem together.
