### ISSUE TITLE
Problem with "ivalid amout"

### ISSUE THREAD

**Issue by kozsich** [ICEPAY/icepay#7]
Hi,

I can't finish order at my eshop [removed for security reasons] .
"invalid amout" appears" When I choose bank and want to finish order at eshop. My eshop provider says, that at Prestashop works everything OK.
![screenshot_20161216173618](https://cloud.githubusercontent.com/assets/24610487/21270289/496239fe-c3b6-11e6-9b24-1661a9051eab.png)

Thanks

**Comment by tsygankov** [comment]
Hi,

Can you please specify the PrestaShop and ICEPAY module versions?

![giro](https://cloud.githubusercontent.com/assets/15112699/21278805/e357054c-c3e5-11e6-9457-40d85ddd240b.PNG)

I've checked your web-shop and looks like you are using GiroCheckout. We are providing support only for ICEPAY payment modules.
